import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { ScanReport, LEAK_TYPE_LABELS } from "./types";
import { formatCurrency } from "./utils";

/**
 * Export a scan report as a PDF file download.
 */
export function exportReportPDF(report: ScanReport, options?: { privacyMode?: boolean }): void {
  const doc = new jsPDF();
  const date = new Date(report.scannedAt);
  const formattedDate = date.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("RevReclaim Revenue Leak Report", 14, 22);

  // Date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120);
  doc.text(`Scanned: ${formattedDate}`, 14, 30);

  // Summary section
  doc.setTextColor(0);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 14, 44);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const summaryItems = [
    `Health Score: ${report.summary.healthScore}/100`,
    `MRR at Risk: ${formatCurrency(report.summary.mrrAtRisk)}`,
    `Leaks Found: ${report.summary.leaksFound}`,
    `Annual Recovery Potential: ${formatCurrency(report.summary.recoveryPotential)}`,
    `Total Subscriptions: ${report.summary.totalSubscriptions.toLocaleString()}`,
    `Total Customers: ${report.summary.totalCustomers.toLocaleString()}`,
    `Total MRR: ${formatCurrency(report.summary.totalMRR)}`,
  ];

  let y = 52;
  for (const item of summaryItems) {
    doc.text(item, 14, y);
    y += 6;
  }

  // Leaks table
  y += 6;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(`Revenue Leaks (${report.leaks.length})`, 14, y);

  const tableData = report.leaks.map((leak, index) => [
    LEAK_TYPE_LABELS[leak.type],
    leak.severity.toUpperCase(),
    leak.title.length > 50 ? leak.title.substring(0, 47) + "..." : leak.title,
    options?.privacyMode
      ? `Customer #${index + 1}`
      : (leak.customerEmail || leak.customerId.substring(0, 15) + "..."),
    formatCurrency(leak.monthlyImpact) + "/mo",
    leak.fixSuggestion.length > 60
      ? leak.fixSuggestion.substring(0, 57) + "..."
      : leak.fixSuggestion,
  ]);

  autoTable(doc, {
    startY: y + 4,
    head: [["Type", "Severity", "Title", "Customer", "Impact", "Fix"]],
    body: tableData,
    theme: "striped",
    headStyles: {
      fillColor: [16, 185, 129],
      textColor: [0, 0, 0],
      fontStyle: "bold",
      fontSize: 8,
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [60, 60, 60],
    },
    alternateRowStyles: {
      fillColor: [245, 245, 245],
    },
    columnStyles: {
      0: { cellWidth: 28 },
      1: { cellWidth: 18 },
      2: { cellWidth: 40 },
      3: { cellWidth: 28 },
      4: { cellWidth: 22 },
      5: { cellWidth: 48 },
    },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by RevReclaim — revreclaim.com | Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.height - 10
    );
  }

  // Download
  const dateStr = date.toISOString().split("T")[0];
  doc.save(`revreclaim-report-${dateStr}.pdf`);
}
