import { NextResponse } from "next/server";

export async function POST(request: Request) {
  try {
    const { email, reportId, summary, leakCount, topLeaks } = await request.json();

    if (!email || !email.includes("@")) {
      return NextResponse.json({ error: "Invalid email" }, { status: 400 });
    }

    if (!reportId) {
      return NextResponse.json({ error: "Missing report ID" }, { status: 400 });
    }

    const mrrAtRisk = summary?.mrrAtRisk
      ? Math.round(summary.mrrAtRisk / 100)
      : 0;
    const recoveryPotential = summary?.recoveryPotential
      ? Math.round(summary.recoveryPotential / 100)
      : 0;

    const topLeaksHtml = (topLeaks || [])
      .map(
        (l: { type: string; impact: number }) =>
          `<li style="margin-bottom:8px;"><strong>${l.type}</strong>: $${l.impact}/mo</li>`
      )
      .join("");

    // Send via Resend if configured, otherwise log
    const resendKey = process.env.RESEND_API_KEY;
    if (resendKey) {
      await fetch("https://api.resend.com/emails", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${resendKey}`,
        },
        body: JSON.stringify({
          from: "RevReclaim <reports@revreclaim.com>",
          to: email,
          subject: `Your Billing Report: $${mrrAtRisk}/mo at risk`,
          html: `
            <div style="font-family:sans-serif;max-width:600px;margin:0 auto;color:#333;">
              <h2 style="color:#000;">Your RevReclaim Billing Report</h2>
              <p>We found <strong>${leakCount} billing leak${leakCount !== 1 ? "s" : ""}</strong> in your account.</p>

              <div style="background:#fef2f2;border:1px solid #fecaca;border-radius:8px;padding:16px;margin:16px 0;">
                <p style="margin:0;font-size:14px;color:#991b1b;">Monthly Revenue at Risk</p>
                <p style="margin:4px 0 0;font-size:28px;font-weight:bold;color:#dc2626;">$${mrrAtRisk}/mo</p>
                <p style="margin:4px 0 0;font-size:13px;color:#666;">Annual recovery potential: $${recoveryPotential}/year</p>
              </div>

              ${topLeaksHtml ? `<h3 style="color:#000;">Top Leaks Found</h3><ul style="padding-left:20px;">${topLeaksHtml}</ul>` : ""}

              <p style="margin-top:24px;">
                <a href="https://revreclaim.com/auth/signup?redirect=/report/${reportId}"
                   style="display:inline-block;background:#10b981;color:#000;font-weight:bold;text-decoration:none;padding:12px 24px;border-radius:8px;">
                  Save This Report & Fix Your Leaks
                </a>
              </p>

              <p style="font-size:12px;color:#999;margin-top:24px;">
                This report was generated by RevReclaim. Create a free account to save it permanently and track your billing health over time.
              </p>
            </div>
          `,
        }),
      });
    }

    return NextResponse.json({ success: true });
  } catch {
    return NextResponse.json(
      { error: "Failed to send email" },
      { status: 500 }
    );
  }
}
